### ISSUE TITLE
Bedarf und Angebote für Testlabore (Geräte und Manpower)

### ISSUE THREAD

**Issue by ELIESCH** [COVID19-PIRAT/Konzept#1]
Hier wäre es gut heruaszufinden, was genau der Bedarf ist.
Die aktuelle Liste ist wie folgt:

Was kann an Unis gefunden werden?

**Geräte**

- PCR-Cycler für Tests
- real time PCR-Cycler für Tests
- Zentrifugen
- Vortexer
- Pipetten

**Verbrauchsgüter**

- Masken FFP 2
- Handschuhe
- Schutzbrillen
- Schutzanzüge
- Handdesinfektionsmittel
- Flächendesinfektionsmittel
- Tupfer für Abstriche
- PCR Testkits (momentan ausreichend vorhanden), z.B. [https://www.who.int/docs/default-source/coronaviruse/protocol-v2-1.pdf?sfvrsn=a9ef618c_2](https://www.who.int/docs/default-source/coronaviruse/protocol-v2-1.pdf?sfvrsn=a9ef618c_2) (Charité), [https://www.fda.gov/media/134922/download](https://www.fda.gov/media/134922/download) (CDC)

**Manpower** 

- Personal in der Testdurchführung
    - TAs/Laboranten/PhDs um Tests durchzuführen**

**In welchen Abteilungen kann man anfragen?**

Beispiele

PCR-cycler:

[https://www.lbgt.wzw.tum.de/ag-bio/ausstattung/](https://www.lbgt.wzw.tum.de/ag-bio/ausstattung/)

[https://wwwt3.ch.tum.de/hydrochemistry/research/bioanalytics-and-microanalytical-systems/laboratories-and-instrumentation/](https://wwwt3.ch.tum.de/hydrochemistry/research/bioanalytics-and-microanalytical-systems/laboratories-and-instrumentation/)

[https://www.bgu.tum.de/sww/service/laborausruestung/](https://www.bgu.tum.de/sww/service/laborausruestung/)

[https://www.nutrition.tum.de/arbeitsgruppen/spanier/](https://www.nutrition.tum.de/arbeitsgruppen/spanier/)

[https://www.alt.wzw.tum.de/index.php?id=83](https://www.alt.wzw.tum.de/index.php?id=83)

Verbrauchsgüter:

[https://www.ch.tum.de/startseite/](https://www.ch.tum.de/startseite/)

[https://www.uni-muenchen.de/einrichtungen/fakultaeten/v18_chemie/index.html](https://www.uni-muenchen.de/einrichtungen/fakultaeten/v18_chemie/index.html)

[https://www.biologie.uni-muenchen.de/](https://www.biologie.uni-muenchen.de/)

[https://www.physik.uni-muenchen.de/](https://www.physik.uni-muenchen.de/)

[https://www.bgu.tum.de/sww/startseite/](https://www.bgu.tum.de/sww/startseite/)

[https://www.biowiss.wzw.tum.de/](https://www.biowiss.wzw.tum.de/)

Manpower (Laborpersonal):

Hier auch Anfrage an Fakultät und darüber wird die Anfrage weitergeleitet an die einzelnen Gruppen, die Personal zur Verfügung stellen können.

**Comment by Julia91457** [comment]
PCR kits sind zur Genüge vorhanden, Fokus kann also auf PCR Cyclern und Verbrauchsmaterial liegen

**Comment by Julia91457** [comment]
Für Manpower: Beispielprojekt an der Charité: https://www.surveymonkey.de/r/WL22F5Z?fbclid=IwAR1tnXm4mmJi7evglqZFHwrWc3MTQjCrWuOGReYk_LCvJRikd7k06GFjlH4

**Comment by markussc1985** [comment]
realtime PCR cyler

**Comment by chaoran-chen** [comment]
Erstellung einer Liste mit Fakultäten, die entsprechende Ausstattung haben (auf ein Bundesland bezogen?)
