### ISSUE TITLE
Finanzieller Ausgleich

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/Konzept#18]
Bekommen die Ausleihenden etwas dafür, dass sie Geräte ausleihen? Gewinnbeteiligung? Wie werden ausgeliehene Mitarbeiter bezahlt?

**Comment by LenaStf** [comment]
Mitarbeitende werden dies zunächst auf ehrenamtlicher/freiwilliger Basis durchführen. Im Idealfall ist mit den auszuleihenden Laboren eine Abmachung zutreffen, dass für die ehrenamtliche Unterstützung der Coronakrise Zeit freigestellt werden kann.

**Comment by chaoran-chen** [comment]
Für Geräte sollte (zumindest für den Anfang) einfach direkte Absprache zwischen Ausleiher und Ausleihendem erfolgen, ob finanzieller Ausgleich gefordert wird bzw geleistet werden kann.
