### ISSUE TITLE
Rechtliche Fragen

### ISSUE THREAD

**Issue by ELIESCH** [COVID19-PIRAT/Konzept#2]
Wie kann so ein Geräte verleih rechtlich organisiert, abgesichert werden.

Wie wird im vorhinein die Funktionsfähigkeit der Geräte sichergestellt und wie können die Geräte in den Kilinikumslaboren / Labordienstleistern eingebunden werden. 

Erste Idee:
https://de.wikipedia.org/wiki/Amtshilfe

**Comment by ELIESCH** [comment]
https://www.gesetze-im-internet.de/vwvfg/BJNR012530976.html#BJNR012530976BJNG002000310

**Comment by Julia91457** [comment]
Können Geräte aus der Forschung in der Diagnostik eingesetzt werden?

**Comment by Julia91457** [comment]
Versicherung von Mitarbeitern/Studenten bei Arbeit in Testlaboren?

**Comment by ELIESCH** [comment]
> 
> 
> Versicherung von Mitarbeitern/Studenten bei Arbeit in Testlaboren?

https://www.forschung.tu-berlin.de/fileadmin/i60/SF_Dokumente/GastwissenschaftlerRichtlinien.pdf
Vielleicht als Gastwissenschaftler?

**Comment by chaoran-chen** [comment]
Input von Markus:
- Gewinnbeteilung? (ist denke ich schwierig, da eine Uni erstmal nicht gewinnorientiert arbeitet)
- Arbeitsbeteiligung sollte als Ehrenamt formuliert sein
- Geräte als Leihgabe zwischen Behörden verkehren lassen
- Ob alle Laborgeräte in einfach in die medizinische Diagnostik überführt werden können ist fraglich (vielleicht können diese "Nachzertifiziert" werden
- Persönliche Versicherung siehe Ehrenamt
- Versicherung der Geräte ist meines Wissens nach nicht möglich für Universitäten (bin selbst in der Vergangenheit schon öfter an dieser Problematik gescheitert)
