### ISSUE TITLE
Erfassung Angebot und Nachfrage

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/Konzept#21]
Für Prototyp: keine Anmeldung/Registrierung nötig, Kontrolle durch direkte Absprache zwischen Ausleiher und Ausleihendem (z.B. Verifizierung von Ausleihenden durch Mitarbeiterausweis o.ä. bei Abholung)

Anbietende stellen ihr Angebot ein (Geräte oder Manpower), geben Kontaktmöglichkeit an (E-Mail)

Suchende stellen Suchanfrage, erhalten Liste mit allen entsprechenden Angeboten in ihrer Nähe und können Anbieter per Mail kontaktieren
Angebot einstellen

über Fragebogen, nötige Felder s.u. (Auswahlmöglichkeiten jeweils in Klammern dargestellt)

Bei Ausfüllen des Fragebogens: Filterung der Antwortmöglichkeiten je nach vorheriger Auswahl --> nur Fragen zu ausgewählten Angebotstypen werden angezeigt

    Angebotstyp: Personal/Gerät/Verbrauchsmaterial (Mehrfachauswahl möglich)
    Name
    Institution
    Adresse
    Mailadresse
    Telefonnummer
    für Geräte: 
        Kategorie (PCR Cycler, RT PCR Cycler, Zentrifuge, Vortexer, Pipette, Sonstiges), 
        exakte Gerätebezeichnung mit Name, Hersteller, Bestellnummer, 
        Standort des Gerätes mit Postleitzahl,
        Anzahl vorhandener Geräte
    für Verbrauchsmaterial: 
        Kategorie (Maske, Schutzkleidung, Schutzbrille, Desinfektionsmittel, Handschuhe, Reaktionsgefäße, Readoutplates, Sonstiges), 
        exakte Materialbezeichnung mit Name, Hersteller, Bestellnummer, 
        Standort mit Postleitzahl,
        vorhandene Menge
    für Manpower: 
        Qualifikation (TA, Laborant, Postdoc, PhD-Student, MSc-Student, BSc-Student, anderes), 
        Institution (welches Forschungsinstitut/Uni/... --> Auswahlliste mit bekannten Unis und Instituten und Möglichkeit, andere einzutragen), 
        Forschungsgruppe (Freitextfeld, keine Pflichteingabe)
        Bereich (Chemie, Biochemie, Genetik, Zellbiologie, Biologie, Virologie, Mikrobiologie, Molekularbiologie, Pharmakologie, Medizin, anderes), 
        Haben Sie Erfahrung in der Durchführung von PCR und RT PCR?
        Anmerkungen (z.B. S1 oder S2-Unterweisung vorhanden, medizinische Qualifikation zur Abstrichentnahme vorhanden)
     Kommentare

Einstellender erhält Link per Mail, um Angebot nachträglich ändern/löschen zu können

**Comment by ELIESCH** [comment]
Fragebogen der Charité Beriln als Beispiel wie der Fragebogen für Mittarbeiter aussehen sollte:
[Questionnair_charite_Beriln.docx](https://github.com/COVID19-PIRAT/Konzept/files/4362609/Questionnair_charite_Beriln.docx)
