### ISSUE TITLE
Qualifikationen

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/Konzept#22]
Welche Qualifikationen von verliehenem Personal sind für welche Aufgaben nötig? Wie werden Qualifikationen überprüft? Wie erfolgt das Einlernen?

**Comment by chaoran-chen** [comment]
Einlernen ist sehr laborabhängig, sollte deshalb vom ausleihenden Labor direkt durchgeführt werden
Gesucht werden Personen mit Erfahrung in der PCR/RT-PCR oder RNA Extraktion (und Freigabe für entsprechende Schutzstufe --> S1 bzw S2),
für Erweiterungen des Projekts: medizinische Ausbildung/Pflege

**Comment by markussc1985** [comment]
In der Sache "Einlernen" sollte man immer im Hinterkopf behalten, dass man momentan auf keinen Fall zu einer weiteren Belastung des Systems werden sollte. Kurze Arbeitsabläufe können sicher vermittelt werden aber das Erlernen neuer Techniken ist momentan nicht möglich. Die Leute sollten daher eine Grundqalifikation mitbringen.
