### ISSUE TITLE
Geräte-/Materialtransport

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/Konzept#24]
Wie werden die Geräte transportiert? Wie stellt man sicher, dass nur kurze Wege nötig sind und rasche Lieferungen möglich sind? Wie vermeidet man Transportschäden?

Transport Möglichkeiten:
Durch Spezielle Unternehmen
https://www.schindlauer.de/betriebsumzug-muenchen/umzug-labore-high-tech-muenchen.html
https://www.geuer.de/laborumzug/
https://www.hebert.de/high-tech-transport-laborumzug/
https://www.umzugs-lauer.de/business-umzug/labor-umzug/

Taxi unternehmen sind ebenfalls gegen Transport Schäden versichert
https://www.daserste.de/information/politik-weltgeschehen/morgenmagazin/service/recht-im-taxi-download-100.pdf

Transport im Dienstfahrzeug
Sind nach aktuellem Kenntnisstand nicht versichert und daher die schlechteste Option

**Comment by ELIESCH** [comment]
Hier müsste halt auch noch geklärt werden wer den Transport bezahlt. Beim abholen kann dann auch die authentifizierung durch Mitarbeiterausweise geschehen, so dass sichergestellt wird, dass auch nur Berechtigte Personen Material abholen

**Comment by ELIESCH** [comment]
Das könnte eventuell auch als FAQ gestaltet werden, da das von den jeweiligen Institutionen individuell geklärt werden muss.
