### ISSUE TITLE
Pitch Video 

### ISSUE THREAD

**Issue by LenaStf** [COVID19-PIRAT/Konzept#27]
Compiling a Pitch Video with our

Problem
Solution 
Next Steps

**Comment by chaoran-chen** [comment]
Vorschlag: einmal Angebot abgeben als Gruppenleiter und einmal Anfrage stellen als Corona-Labor

**Comment by ELIESCH** [comment]
[We are a team of chemists.txt](https://github.com/COVID19-PIRAT/Konzept/files/4365558/We.are.a.team.of.chemists.txt)
