### ISSUE TITLE
FAQs schreiben

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/Konzept#28]

**Comment by ELIESCH** [comment]
Reaktionsgef#ße für die PCR --> Reaktionsgefäße für die PCR

**Comment by ELIESCH** [comment]
ie können sich die beteiligten Behörden rechtlich gegenübertreten? --> fehlt das W am Anfang

die links haben alle gepasst

**Comment by ELIESCH** [comment]
FAQ ist jetzt auch Rechtlich überprüft worden von  MENT_Stephanie Hesse :
Die Zusammenfassung ist schon mal super. Die Amtshilfe hat ihre Grundlage tatsächlich im Grundgesetz (Art. 35). Das VwVfG enthält nähere Ausführungen ebenso wie das Zehnte Sozialgesetzbuch (SGBX). Tatsächlich finde ich es schwierig pauschale Angaben zu machen. Erste Voraussetzung ist jedenfalls immer, dass es sich auch um Behörden handelt, die da interagieren. Grundsätzlich hat eure Idee m. E. sehr gute Grundlagen. Bei der Amtshilfe geht es ja darum, dass diese grds. kostenlos ist. Die Versicherung dürfte auch durch die DGUV abgesichert sein. Grenzen sind natürlich bei Geschäftsmäßigkeit und DSGV erreicht. Spätere individuelle Prüfung ist unerlässlich. Hoffe, euch geholfen zu haben und weiterhin viel Erfolg
