### ISSUE TITLE
Fortsetzung über Hackathon hinaus

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/Konzept#29]
- Gerätenutzung in Diagnostik abklären
- Mailadressen suchen, um Werbung zu machen
- Betreiber der Plattform? zB lrz
- Einbinden von Krankenhäusern/Rettungsdienst

**Comment by markussc1985** [comment]
Die meisten Großgerätehersteller haben auch Gerätepools in den Firmen, z.B als Vorführgerät, ggf. könnte man die mal per Werbung ansprechen.
