### ISSUE TITLE
Checkmark für Angebot Mensch ergänzen

### ISSUE THREAD

**Issue by ELIESCH** [COVID19-PIRAT/Konzept#32]
Hey können wir bei dem Angebot Mensch noch einen checkmark machen, bei dem angekreuzt wird, dass man weiß, dass die ehrenamtlichen arbeiten außerhalb der Arbeitszeiten macht und dies mit seinem vorgesetzten abgesprochen hat

z.B.
° Meine Eherenamtiliche Tätigkeit findet außerhalb meiner Arbeitszeiten statt und ist mit meinem vorgesetzten abgeklärt.

-->das muss man dann halt bestätigen

**Comment by lvordemann** [comment]
Wird gemacht
