### ISSUE TITLE
Verbesserungsvorschläge Webseite

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/Konzept#33]
- [x] Seite sieht super aus, aber beim Verbrauchsmaterial müssten die in Klammernstehenden Möglichkeiten noch in ein Dropdownmenü

**Comment by chaoran-chen** [comment]
Bei mehreren Checkboxen+Bezeichnung nebeneinander: mehr Abstand zwischen Kästchen und nicht-zugehöriger benachbarter Bezeichnung
Bei Mengen: Angabe von Einheiten möglich machen (z.B ein Feld für die Anzahl und ein Dropdownmenü für die Einheit --> Packung, Stück, sonstiges)

**Comment by markussc1985** [comment]
Wort Ressourcen anstatt Güter

**Comment by chaoran-chen** [comment]
Ich finds schon sehr gut! ein paar anmerkungen noch die mir beim ersten durchschauen aufgefallen sind:
- Kann man die Neuigkeiten in die rechte Spalte verschieben oder ist das zu aufwendig? Wenn sie ganz unten stehen findet man sie kaum
- Dunklere Schrift fände ich immer noch gut, Vorschlag Inline:216 --> #595959 ;)
- Welche FAQ-Version ist denn das aktuell auf der Seite? Die entspricht nicht der in Notion, könnte man das ändern?
- In den FAQs sind Überschriften zT zu nah an den vorhergehenden Absätzen
- kann man die FAQs als Dropdown machen? so dass man Allgemeines, Für Anbietende und Für Suchende sieht und durch Klick ausklappen kann
- ich bin nicht ganz glücklich mit dem verpixelten look vom Banner-Bild, könnte man da mal ein unverpixeltes reinpacken?
- wenn man einen Mensch hinzufügt sollte es bei Bereich ein Dropdown menü geben, nachdem man später danach filtern kann und es ist ein Tippfehler ganz unten bei ehrenamtlich

**Comment by chaoran-chen** [comment]
die dropdown-Inhalte bei Geräte stimmen noch nicht (soll: PCR Cycler, RT PCR Cycler, Zentrifuge, Vortexer, Pipette, Sonstiges)

**Comment by chaoran-chen** [comment]
Typo: Verantwor**t**liche Person bei Kontaktdaten

**Comment by chaoran-chen** [comment]
Bei Kategorie in Geräten: PCR Cycler (nicht wie aktuell PRC)

**Comment by chaoran-chen** [comment]
bei Personenerstellung: Typo in ehrenamtlich
