### ISSUE TITLE
Über uns Reiter auf der Webseite

### ISSUE THREAD

**Issue by lvordemann** [COVID19-PIRAT/Konzept#34]
Die Überlegung ist, dass wir uns als Hackathon Team in dem Über uns Reiter auf der Webseite vorstellen. Wollen wir das? Wir kennen noch nicht den zukünftigen Betreiber der Seite, wie gehen wir damit um? Mit oder ohne Fotos? Bitte mitdiskutieren!

**Comment by markussc1985** [comment]
Ich hab auf dem feld nicht so die Erfahrung... Wegen mir würde das auch mit Bild gehen. Dann solte jeder über ich ein zwei Sätze formulieren...

**Comment by ifeelit** [comment]
Ich würde es eher ohne Bild machen. Man muss ja nicht mit uns in Kontakt treten.

**Comment by chaoran-chen** [comment]
ich hab mich jetzt beispielshalber mal in notion vorgestellt...wollt ihr das so/anders/wie konkret anders?
