### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/Konzept#35]
Wir brauchen noch ein Logo, nehme ich an?

**Comment by ELIESCH** [comment]
Hey vielleicht sollten wir das offizielle Logo vom Hackathon noch mit in die Seite rein tun damit man die Webseite auch einordnen kann
 https://drive.google.com/drive/folders/1zzrE57uVZcqAXv6TN01PQqS7bfB0MuxD

**Comment by chaoran-chen** [comment]
Vorschlag wohin? Vielleicht kann man das Logo auf der Über uns Seite einbinden? Oder ganz unten in die Fußzeile?

**Comment by ELIESCH** [comment]
Ich fände es in der Fußzeile gut dann wäre es auf allen Seiten mit drauf. Ich glaub das wäre wichtig.

**Comment by chaoran-chen** [comment]
![Unbenannt](https://user-images.githubusercontent.com/18666552/77246397-0e708180-6c27-11ea-8d2e-99a346d98f8b.JPG)
![picturemessage_pwarsdfq 5kz](https://user-images.githubusercontent.com/18666552/77246400-16c8bc80-6c27-11ea-9df7-80305d822173.png)

**Comment by lvordemann** [comment]
Piratenlogo ist auf Webseite
