### ISSUE TITLE
Email Text

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/Konzept#37]
Nach dem Erstellen eines Angebotes wird eine Email versendet, die einen Link für die Bearbeitung enthält. Wir bräuchten den Text für die Email.

**Comment by ELIESCH** [comment]
nur zur info ich fang das jetzt einfach auf notion an

**Comment by ELIESCH** [comment]
https://www.notion.so/Email-f-r-Teilnehmer-ec65aa30b39c44b0ac96c98d99a703b2
