### ISSUE TITLE
Emails

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/Konzept#42]
Das System sendet Emails an Nutzer ab:

- Bestätigungsmail nach Angeboterstellung
- Bestätigungsmail, dass eine Anfrage über das Kontaktformular an einen Anbieter gesendet wurde.
- Die Email, die der Anbieter bekommt, wenn ein Interessent über das Kontaktformular ihn kontaktiert.

Was sollen diese Email konkret beinhalten? Welche rechtlichen Hinweise sind beizufügen, insbesondere wenn wir selber hosten sollten?

@COVID19-PIRAT/experten

**Comment by ELIESCH** [comment]
https://www.notion.so/Nachricht-an-Testlabore-f9d9a4e99927405eac1f9bd07d5a315a

https://www.notion.so/Nachricht-an-Universit-ten-626ad3121af64f2c933a55d73e351b35

Wenn hier nochmal jemand drüber schauen könnte wäre das super.

**Comment by chaoran-chen** [comment]
Bitte nach "In Entwicklung" schieben, wenn die Texte als final gelten.

**Comment by Julia91457** [comment]
In der Mail die man bekommt wenn jeamnd interesse an einer ressource hat, sollte auch drin stehen worauf genau sichdie anfrage bezieht, falls jemand mehrere ressourcen eingestellt hat (momentan stehen nur kontaktdaten des anfragenden drin)

**Comment by Julia91457** [comment]
Texte für automatische antworten in DE und EN sind soweit, gerne nochmal drüber schauen, wenn wer zeit hat, nachrichten an Labore und unis werden gerade korrekturgelesen

**Comment by chaoran-chen** [comment]
Erledigt in d63df3fbe8385ac68f84c369f2a56ecc8e272a9d

Danke für die wundervollen Vorlagen!
