### ISSUE TITLE
Verantwortlicher in Impressum/Datenschutzerklärung

### ISSUE THREAD

**Issue by Julia91457** [COVID19-PIRAT/Konzept#44]
Wir sollten entscheiden, wer als Verantwortlicher bzw. Datenschutzbeauftragter eingetragen wird, wenn wir selbst hosten und das dann auch machen

**Comment by Julia91457** [comment]
Ich versuch nochmal wen über Impressum und Datenschutz drüber schauen zu lassen (von der d·bug GmbH, der hat da zumindest erheblich mehr Erfahrung als ich)

**Comment by Julia91457** [comment]
unsere Datenschutzerklärung bezieht sich grade direkt im ersten Absatz noch auf Unternehmen, das müsste noch geändert werden

**Comment by Julia91457** [comment]
habs überarbeitet, wäre gut wenn nochmal jemand drauf schauen kann unds dann möglichst schnell auf die seite kommt, wenn soweit alles passt

**Comment by chaoran-chen** [comment]
Erledigt in https://github.com/COVID19-PIRAT/frontend/commit/85fe5ddb5dd7d17ef6a6e1cf46ed71c7e16f2b36
