### ISSUE TITLE
reCAPTCHA/Cookie-Hinweis

### ISSUE THREAD

**Issue by Julia91457** [COVID19-PIRAT/Konzept#45]
uU brauchen wir für die Verwendung von reCAPTcHA einen Cookie-Banner, auf jeden Fall sollten wir es in die Datenschutzerklärung mit aufnehmen. Scheinbar setzt reCAPTCHA nicht zwingend Cookies, wie ist das auf unserer Seite?

Folgendes habe ich gefunden:

- Hinweis des LDA zur reCAPTCHA-Nutzung: Website-Betreiber sollten unbedingt Alternativen prüfen. Wird dennoch Google reCAPTCHA eingebunden, muss sich der Verantwortliche im Klaren sein, dass er den rechtmäßigen Einsatz gem. Art. 5 Abs. 1, 2 DS-GVO nachweisen können muss. Wer nicht darlegen kann, wie Google die Nutzerdaten verarbeitet, kann den Nutzer nicht transparent informieren und den rechtmäßigen Einsatz nicht nachweisen.

- reCAPTCHA-Datencshutzerklärung (Beispiel): https://www.adsimple.de/datenschutzerklaerung/google-recaptcha/ --> könnte man übernehmen bzw sinnvoll kürzen, sollte für unsere Zwecke ausreichend sein

- Hinweise von Google: https://www.google.com/about/company/user-consent-policy/

**Comment by chaoran-chen** [comment]
Laut Flo: Auch notwendige Cookies sind erst nach dem Akzeptieren durch den Nutzer zu setzen erlaubt!

**Comment by Julia91457** [comment]
ist in notion in impressum integriert

**Comment by chaoran-chen** [comment]
Der Empfehlung von Flo folgend wird der folgende Hinweis neben die reCAPTCHA Elemente gesetzt:

"reCAPTCHA von Google verwendet Cookies, um zu speichern, dass Sie das Captcha bestätigt haben. Die Zustimmung zu diesem Cookie ist von unserer Seite für das Anlegen eines Angebotes notwendig. Sie können den Cookie im Nachhinein selbstständig wieder löschen."
