### ISSUE TITLE
Fehler u.ä.

### ISSUE THREAD

**Issue by Julia91457** [COVID19-PIRAT/Konzept#46]
**Typos/Textvorschläge:**
- [x] Angebot einstellen --> Hiermit versichere ich**,** die Datenschutzerklärung ...

- [x] Angebot einstellen --> Ressourcen **Bitte** mindestens

- [x] nach Absenden von Angebot: das "Angebot Übersicht" klingt nicht so schön, vielleicht einfach nur Übersicht oder Angebotsübersicht?

- [x] nach Absenden von Angebot: wenn ich den Link der mir angezeigt wird kopiere, komme ich auf eine leere Seite (der Link aus der E-Mail funktioniert aber, Unterschied zwischen den beiden ist ein offer (von Webseite) --> https://pirat.chaoran-chen.de/offer/MeldjKgh3krQraPUPYJGgLiXcHPh7z bzw. change (aus E-Mail) --> https://pirat.chaoran-chen.de/change/MeldjKgh3krQraPUPYJGgLiXcHPh7z )

- [x] bei Kontakt zu Anbieter nach Suche: Nutzen Sie dieses Kontaktformular**,** um ...

 - [x] ebd: statt "Angebot erstellen" vllt "Nachricht absenden" als Beschriftung des Sendebuttons

- [x] ebd.: nach absenden der Nachricht: "Vielen Dank für Ihre Nachricht. Sie wurde an den Anbieter übermittelt, er wird sich direkt mit Ihnen in Verbindung setzen. (damit klarer wird, dass wir da dann raus sind), in die Nachricht die an den Anbieter geht evtl auch noch mit rein schreiben, dass er jetzt dran ist und sich direkt beim anfragenden melden sollte

- [x] Textvorschlag Kontaktformular:
Wenn Sie Fragen, Wünsche oder Anregungen haben, freuen wir uns, wenn Sie Kontakt mit uns aufnehmen. Benutzen Sie einfach das Kontaktformular, wir melden uns schnellstmöglich per E-Mail oder Telefon bei Ihnen!

**noch zu erledigen:**
- [x] Kontakt als eigenen Menüpunkt (außer das wurde mittlerweile wieder gekickt?)

- [ ] die FAQs haben vmtl noch einen Korrekturdurchlauf nötig, ich kümmere mich am Wochenende darum

- [ ] Mustervertrag selbst erstellen (wird heute nachmittag gemacht)

- [ ] Übersetzung (wird heute/am Wochenende erledigt)

**Anregungen:**
- [x] statt dem roten "Bitte ausfüllen!" ein fettgedrucktes "Pflichtangabe" ind Klammern? das rot wirkt so aggressiv. (oder gleich ein Sternchen wies beim Kontaktformular wenn man material/Personal anfragen will, schon ist. auf jeden Fall einheitlich machen!)

- [x] bei Helfer einstellen: Hiermit wird bestätigt, dass der Helfer die Tätigkeit ehrenamtlich außerhalb der Arbeitszeiten **ausführen wird**.

- [ ] beim Kontaktformular: Könnte man das nicht Rückruf anfragen sondern einfach Kontakt nennen? und dann Name und Thema als Pflicht, Entweder TelNr oder Mailadresse auch als Pflicht (wenn das geht) und statt Anmerkung "Ihre Nachricht", zusätzlich noch ein Auswahlfeld mit "Bitte kontaktieren Sie mich über" und dann Mail bzw Telefon als Auswahlmöglichkeiten --> dann müssen wir nicht die Mailadresse angeben, ich finde ne gmail-Adresse wirkt nicht so professionell, reicht ja wenn davon dann ne Antwort kommt

**Comment by chaoran-chen** [comment]
Die übrigen Sachen werden in anderen Issues bearbeitet.
